language: node_js
node_js:
  - "8"
  - "9"

cache: yarn

install: yarn
script: echo "npm test temporarily disabled"
jobs:
  include:
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
