language: node_js

node_js:
  - "9"
  
#script: echo "npm test temporarily disabled"
branches:
  only:
    - master
    
install:
  - npm install

script:
  - npm test
    
before_deploy:
- npm version patch

deploy:
  provider: releases
  email: harith.13@itfac.mrt.ac.lk
  api_key: d146c65b-23d7-4726-b301-99c7f1a3b453
  on:
    branch: master

